#version: '3.8'
#
#networks:
#    my-laravel-network:
#        driver: bridge
#
#services:
#    db:
#        image: mysql:8.0
#        environment:
#            MYSQL_ROOT_PASSWORD: yourpassword
#            MYSQL_DATABASE: laravel_db
#        ports:
#            - "3306:3306"
#        networks:
#            - my-laravel-network
#
#    app:
#        build:
#            context: .
#            dockerfile: Dockerfile
#
#        depends_on:
#            - db
#        ports:
#            - "8000:8000"
#        networks:
#            - my-laravel-network
#

version: '3.8'

networks:
    my-laravel-network:
        driver: bridge

services:
    db:
        container_name: db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: yourpassword
            MYSQL_DATABASE: laravel_db
        ports:
            - "3306:3306"
        networks:
            - my-laravel-network

    app:
#        image: ihorsamolich/laravel-docker
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8000:8000"
#        volumes:
#            - uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - my-laravel-network
